version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: sellpoint
      POSTGRES_USER: sellpoint
      POSTGRES_PASSWORD: sellpoint
    volumes:
      - sellpoint_pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - BACKEND_PORT=${BACKEND_PORT}
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:5001"
    command: ["gunicorn", "wsgi:app", "-b", "0.0.0.0:5001", "--workers", "2"]

volumes:
  sellpoint_pg:
